version: 2

.openssl_job: &openssljob
  docker:
    - image: ${IMAGE}
  steps:
    - checkout
    # we need to first build and install OpenSSL 1.0.2 to ensure that liboqs is compiled against OpenSSL 1.0.2, then compile OQS-OpenSSL 1.0.2 against liboqs
    - run:
        name: Clone plain OpenSSL 1.0.2
        command: |
          mkdir /tmp-build
          cd /tmp-build
          git clone --single-branch --branch OpenSSL_1_0_2t https://github.com/openssl/openssl.git
    - run:
        name: Build plain OpenSSL 1.0.2
        command: |
          mkdir /tmp-install
          cd /tmp-build
          cd openssl
          ./Configure no-shared --prefix=/tmp-install linux-x86_64 -lm
          make
          make install_sw
    - run:
        name: Clone liboqs
        command: cd oqs_test && scripts/clone_liboqs.sh
    - run:
        name: Build liboqs
        environment:
          OPENSSL_SYS_DIR: /tmp-install
        command: cd oqs_test && scripts/build_liboqs.sh
    - run:
        name: Build OQS-OpenSSL 1.0.2
        command: cd oqs_test && scripts/build_openssl.sh
    - run:
        name: Run unit tests
        command: cd oqs_test && mkdir -p test-results && python3 -m nose --rednose --verbose --with-xunit --xunit-file=test-results/nosetests.xml
    - store_test_results: # Note that this command will fail when running CircleCI locally, that is expected behaviour
        path: oqs_test/test-results

jobs:
  debian-buster-amd64:
    <<: *openssljob
    environment:
      IMAGE: dstebila/liboqs:debian-buster-amd64-0.1.0
      ARCH: x64
      LIBOQS: master
      OPENSSL: 102
  ubuntu-xenial-x86_64:
    <<: *openssljob
    environment:
      IMAGE: dstebila/liboqs:ubuntu-xenial-x86_64-0.1.0
      ARCH: x64
      LIBOQS: master
      OPENSSL: 102

workflows:
  version: 2

  build:
    jobs:
      - job1:
          filters:
            branches:
              ignore:
                - /.*1.0.2.*/
                - /.*102.*/
